import uuid
from datetime import datetime
from app.models.schemas import ReportRequest, ReportResponse, HealthSummarySchema

class ReportService:
    """
    Service generating printable medical summary briefs and clinical report records.
    """

    async def create_report(self, request: ReportRequest) -> ReportResponse:
        report_id = f"REP-{uuid.uuid4().hex[:8].upper()}"
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        # Synthesize physician brief
        symptoms_str = ", ".join(request.summary.symptoms) if request.summary.symptoms else "General Malaise"
        physician_brief = (
            f"Patient Age: {request.patientAge} | Gender: {request.patientGender}\n"
            f"Triage Urgency: {request.summary.urgency.value.upper()}\n"
            f"Identified Symptoms: {symptoms_str} (Duration: {request.summary.duration or 'Not specified'})\n"
            f"Care Recommendation: {request.summary.recommendation}\n"
            f"AI Confidence Score: {request.summary.confidence}%\n"
            f"Total Conversation Turns: {len(request.history)}"
        )

        return ReportResponse(
            sessionId=request.sessionId,
            reportId=report_id,
            generatedAt=timestamp,
            summary=request.summary,
            physicianBrief=physician_brief,
            disclaimer="This report is generated by Sanjeevani AI (Google Gemma Backend). It is intended solely as an initial triage assessment summary for licensed healthcare clinician review."
        )

report_service = ReportService()
